name: Build Mobile NDLLs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build for ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - platform: android
            os: ubuntu-latest
          - platform: ios
            os: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        if: matrix.platform == 'android'
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Setup Haxe
        if: matrix.platform == 'ios'
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Setup Android NDK
        if: matrix.platform == 'android'
        id: setup-ndk
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r21c
          add-to-path: false

      - name: Install Haxe Dependencies
        run: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install hxcpp
          haxelib run lime setup -y

      - name: Configure Android
        if: matrix.platform == 'android'
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true

      - name: Rebuild Android NDLL
        if: matrix.platform == 'android'
        run: |
          lime rebuild . android

      - name: Rebuild iOS NDLL
        if: matrix.platform == 'ios'
        run: |
          lime rebuild . ios

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ndll-${{ matrix.platform }}
          path: ndll/
